#!/bin/bash -e

CUR_DIR=$(pwd)
TARGET_DIR=${CUR_DIR}/output
CUSTOM_CONFIG=${CUR_DIR}/custom_config
TOOLCHAIN=arm-linux-gnueabihf
REV=r2

mkdir -p $TARGET_DIR
cd linux
git reset --hard HEAD
KERNEL_VERSION=$(make kernelversion)
KERNEL_TARGET_FILE_NAME=rpiq-kernel-$KERNEL_VERSION-$REV

echo "build vexpress kernel $KERNEL_TARGET_FILE_NAME"
make ARCH=arm vexpress_defconfig

echo "CONFIG_CROSS_COMPILE=\"$TOOLCHAIN\"" >> .config
cat ${CUR_DIR}/rpiq_config >> .config
if [ -f $CUSTOM_CONFIG ]; then
    echo "adding extra $CUSTOM_CONFIG"
    echo >> .config
    echo "# custom config" >> .config
    cat $CUSTOM_CONFIG >> .config
fi

make ARCH=arm CROSS_COMPILE=${TOOLCHAIN}- olddefconfig
make -j2 ARCH=arm CROSS_COMPILE=${TOOLCHAIN}- bzImage dtbs
cp arch/arm/boot/zImage $TARGET_DIR/$KERNEL_TARGET_FILE_NAME
cp arch/arm/boot/dts/vexpress-v2p-ca9.dtb $TARGET_DIR

cd $CUR_DIR
